### ISSUE TITLE
Add: Sitemap

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/cdweb1801#11]
[Jigsaw](jigsaw.tighten.co) can create output as [whatever file type](http://jigsaw.tighten.co/docs/other-file-types/). So you can create a sitemap using `XML`.

**Comment by Jubeki** [comment]
Should it look something like that?
[https://www.dropbox.com/s/wz3gb10udvdcxfj/sitemap.xml?dl=0](https://www.dropbox.com/s/wz3gb10udvdcxfj/sitemap.xml?dl=0)

If it something like that than I can only think of iterating over all collections but then not all pages are included. Or does Jigsaw has such a tool?

**Comment by minthemiddle** [comment]
Yes, exactly like this. For a quick pages hack, you might refer to PHP's [scandir](http://php.net/manual/de/function.scandir.php) and just return all `*.blade.php` files in `/source`. There was a discussion on how to get pages on Github [recently](https://github.com/tightenco/jigsaw/issues/175#issuecomment-355971443), but it does not seem to have a solution yet.

**Comment by Jubeki** [comment]
Look here for more information about how to make a sitemap with jigsaw (using events):
[https://github.com/tightenco/jigsaw/pull/189](https://github.com/tightenco/jigsaw/pull/189)

**Comment by minthemiddle** [comment]
@Jubeki Great, will wait for it to be merged into core.
