### ISSUE TITLE
Add: Coaches at camp

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/cdweb1801#12]
Similarily to partners who get referenced via `YAML Frontmatter` to a camp (e.g. `camps: BER1802`) and displayed under a camp, coaches should also be added.

Infos to add:

- Firstname
- Lastname
- Twitter
- Github
- Link to website
- Image

**Comment by toorusr** [comment]
Solved? #154

**Comment by toorusr** [comment]
Fix #154
