### ISSUE TITLE
Bug: Flexbox around text not correct at 430px width

### ISSUE THREAD

**Issue by toorusr** [CodeDesignInitiative/cdweb1801#147]
# What did you expect?
I expected to see a responsive text at https://code.design/initiative under Spenden.

# What did you get instead?
I got that at 438px width:
![Flexbox Bug](https://user-images.githubusercontent.com/33150948/40240371-b7e5a0ce-5ab8-11e8-94c0-9ded62f5e87e.png)

It maybe has to do with the tailwind flexbox around it.

**Comment by minthemiddle** [comment]
Solved via #299
