### ISSUE TITLE
Enhancement: Code is partly very illegible

### ISSUE THREAD

**Issue by toorusr** [CodeDesignInitiative/cdweb1801#150]
# What did you expect?
Easy to modify code and well structured files.

# What did you get instead?
Code that is partly very illegible and hard to understand.

# What were your exact steps to get to your problem?
Contributing to this repository.
# What to do against it?
Strictly reformat and enhance every file.
##### Some points where to start:
- [x] source/*.blade.php #153  
- [ ] source/_layout/*.blade.php
- [ ] source/_partials/*.blade.php

**Comment by minthemiddle** [comment]
- Auto formatting blade files does not work in Sublime (yet). That's why I did not format it in any way
- Maybe Visual Studio Code can do
- Or there is an external tool to do the reformatting

**Comment by toorusr** [comment]
The method I have used was to just manually reformat the blade files. 
I know, it's not really efficient, but I will now look for an automated solution.
(I do format format all by code.)
