### ISSUE TITLE
Bug: Campy assign now button on non active camps

### ISSUE THREAD

**Issue by toorusr** [CodeDesignInitiative/cdweb1801#177]
# What did you expect?
I did expect, that there would not be a assign now button on an outdated camp.

# What did you get instead?
I did actually get 2 buttons which told me to sign up now for a camp in the past.

# What were your exact steps to get to your problem?
Just visiting a outdated camp site.

**Comment by minthemiddle** [comment]
Good point. Did not take that into account when putting the new button online. Actually the plan is, to get an embeddable form for signing up at the camp again - but with a Campy backend. Anyway, this here is an issue we need to fix asap.

**Comment by toorusr** [comment]
Okay.
'asap'?

**Comment by minthemiddle** [comment]
Solved unintentionally via #184
