### ISSUE TITLE
Travis should only build on master branch

### ISSUE THREAD

**Issue by Jubeki** [CodeDesignInitiative/cdweb1801#18]
[Stackoverflow](https://stackoverflow.com/questions/12878568/travis-ci-triggers-build-only-for-master-branch-in-github-repo)

Add to .travis.yml:
`branches: 
  only: 
    - master`

[Blog Travis](https://blog.travis-ci.com/2017-05-11-introducing-build-stages)
Content: Only do something if something other was succesful

**Comment by Jubeki** [comment]
[Travis Documentation](https://docs.travis-ci.com/user/build-stages)
komplette Lösung, für branch und so.

**Comment by minthemiddle** [comment]
Actually, travis should also build on PRs, but not try to push the built site to Netlify.

**Comment by Jubeki** [comment]
[Travis Documentation](https://docs.travis-ci.com/user/build-stages)

Like in in comment before:
For this are the build stages. one stage like the one to push to netlify ist one build stage and only happens if the branch is the master.
And another build stage is the jigsaw build which happens every time.

**Comment by minthemiddle** [comment]
That was just a specification which was not in the original issue.
I already read how it works theoretically, but one needs to test it out with a demo repo first, I guess.
PR welcome, @Jubeki :)

**Comment by Jubeki** [comment]
Ok i test it with a personal netlify account.

**Comment by Jubeki** [comment]
Please help me...

I don't know how to fix the Problem with the deploy to netlify:
[https://app.netlify.com/sites/festive-wilson-61ad30/deploys/5a919209a6188f56597824d0](https://app.netlify.com/sites/festive-wilson-61ad30/deploys/5a919209a6188f56597824d0)

I cloned cdweb1801 to [travis-test](https://github.com/Jubeki/travis-test)
Then netlify tries to deploy the site but it doesn't work.

**Comment by minthemiddle** [comment]
@Jubeki You need to set a env var for PHP7. Right now Jigsaw does simply not install. See my comment on an issue [over at Netlify's build image](https://github.com/netlify/build-image/issues/147#issuecomment-368224909) on how to solve that.

**Comment by Jubeki** [comment]
[https://github.com/Jubeki/travis-test](https://github.com/Jubeki/travis-test)
Can somebody do a pull request please?
The site is being build with this config now I want to try if it only build on `branch = master`

**Comment by minthemiddle** [comment]
I thought your idea was to skip Travis and go for Netlify build directly.
This has been possible since a few days (as described [her](https://medium.com/@martin_betz/just-commit-to-git-build-static-pages-continuously-using-php-generators-like-jigsaw-on-netlify-4a3a18327ffa).

I think it's an excellent idea! One less tool, and probably also faster than Travis because the tools (composer, yarn) are already installed…

**Comment by Jubeki** [comment]
But then you don't have the jigsaw check anymore. Or do you still want to build with travis and fetch directly from netlify?

**Comment by minthemiddle** [comment]
Close for now as per #53

**Comment by minthemiddle** [comment]
Btw, [pull requests](https://www.netlify.com/blog/2016/07/20/introducing-deploy-previews-in-netlify/) are creating deploy previews with own specific domain…
