### ISSUE TITLE
Bug: player buttons over complete site

### ISSUE THREAD

**Issue by toorusr** [CodeDesignInitiative/cdweb1801#180]
Somehow after PR #175 the player buttons are going wild.
I have tested the website on like three different devices and browsers and the bug is definitely a source problem and does not have to do with browsers or devices.

![screenshot at 2018-06-08 21-47-13](https://user-images.githubusercontent.com/33150948/41172813-4e97130c-6b55-11e8-9e9b-e5c1d3833302.png)

## Fix?
Maybe at first revert the PR #175 than we can look what the problem is.

**Comment by minthemiddle** [comment]
Needs more testing.

**Comment by toorusr** [comment]
Woah, that was quick
