### ISSUE TITLE
 Bug: Ambassador link to google form does not exist anymore

### ISSUE THREAD

**Issue by toorusr** [CodeDesignInitiative/cdweb1801#182]
There are still two redirects in the `_redirects` file which redirect to a nonexistent google form.

**Comment by toorusr** [comment]
@minthemiddle What should we do?

**Comment by minthemiddle** [comment]
Here's the correct Google link, you can just fix the redirect: https://goo.gl/forms/wSxYfXEnpnCC14pI3
