### ISSUE TITLE
Cut: old example coach

### ISSUE THREAD

**Issue by toorusr** [CodeDesignInitiative/cdweb1801#201]
There is currently an old example coach which is unnecessary for the examples called `Peter Limbach`. 

### Fix
Remove the file `source/_coaches/limbach.md` which contains the example information about `Peter Limbach`.

**Comment by minthemiddle** [comment]
Well, Peter is an existing coach from Berlin. But still, just an example for now. Should not exist as a sole coach.

**Comment by toorusr** [comment]
Yeah, but he did not really add any information about him self in there.
