### ISSUE TITLE
Critical Bug: The build is failing no matter what I do 

### ISSUE THREAD

**Issue by toorusr** [CodeDesignInitiative/cdweb1801#209]
The build of the site fails since I fixed some information for the bon1808 camp.
It gives me the following build error:

```
1:11:05 AM: Executing user command: ./vendor/bin/jigsaw build production && cp _redirects build_production/_redirects
1:11:05 AM: In CollectionDataLoader.php line 92:
1:11:05 AM:   No matching collection item handler
1:11:05 AM: build [--pretty PRETTY] [--] [<env>]
```
*Full log at [netlify](https://app.netlify.com/sites/code-design-initiative/deploys/5b43eb7ddd28ef7e7931a9a0)*

I do not now what to do...
I will now try going back 5 commits after HEAD and look what it does.

Also I would prefer if travis would be turned on. May be that is also something I could try.

**Comment by minthemiddle** [comment]
Naughty error: Missing file extension.

How I quickly caught it:
- Searched for `No matching collection item handler` in [Jigsaw's issues](https://github.com/tightenco/jigsaw/issues?utf8=%E2%9C%93&q=No+matching+collection+item+handler)
- Read the [one result](https://github.com/tightenco/jigsaw/pull/161)
- Figured it was about file extensions that Jigsaw does not support
- Searched the latest commits and found the file that had a missing `.md` extension

**Comment by toorusr** [comment]
Oh... I am feeling really dumb right now :(

**Comment by minthemiddle** [comment]
No worries, sometimes you need an extra pair of eyes. That's why we are open source…
