### ISSUE TITLE
Discussion: Travis CI, Netlify direct or other CI

### ISSUE THREAD

**Issue by toorusr** [CodeDesignInitiative/cdweb1801#224]
Under this issue we can discuss about how we will handle the building and publishing process of the website.

Currently we're building the website directly using Netlify.
I'll test the build process on both travis and netlify and will check what service is better to build the website we want.

**Comment by Jubeki** [comment]
I think we should just stick to Netlify. I don't really see the need to switch to a CI.

**Comment by minthemiddle** [comment]
Me neither. Netlify is set up so it will even build PRs, so everyone can check how her/his changes would look live.
