### ISSUE TITLE
Speed up build by caching yarn and composer packages

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/cdweb1801#27]
- Building the site takes around 4 minutes right now via Travis
- By far the most time consuming task is installing `yarn` and `composer install`
-  These `JS` and `PHP` requirements do not change so often, so rebuilding them on every build is a huge waste of time
- Here is a first attempt on a fork to cache `yarn` which unfortunately did fail: https://github.com/minthemiddle/cdweb1801/blob/add-yarn-cach/.travis.yml

**Comment by Jubeki** [comment]
[Travis yarn-cache](https://docs.travis-ci.com/user/caching/#yarn-cache)
[Travis composer-Cache](https://blog.wyrihaximus.net/2015/07/composer-cache-on-travis/)

Maybe this websites will help to fix the issue with the cache.

**Comment by minthemiddle** [comment]
As changes are 100% content and none for things we need to build via `gulp` so far (e.g. `Sass` or `Javascript` bundling), the fastest way to build is to just skip everything `npm` and `yarn`. 

- This happened via #53 
- Travis build is disabled for the moment
- Building happens via Netlify
- Building went down from apprx. `4:30` to `0:25`(-90%!)
