### ISSUE TITLE
Update: Use new Netlifly CLI

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/cdweb1801#7]
So far we have been using Netlify's `Node` commandline tool (CLI) to push the generated HTML from `Travis` to `Netflify`.

This is defined via `travis.yml`:

```yml
script:
  - netlify -t $NETLIFY_TOKEN deploy --site-id sharp-goldstine-eda64e -p build_production
```

The security token is passed as a `Travis` environment variable.

One big downside to the current CLI that we cannot pass commit messages to Netlify. Hence every build does not tell us in Netlify what we changed `No deploy message`.

Switch the deployment to Netlify to their new `Golang` [CLI](https://github.com/netlify/netlifyctl) where you can just pass a `m` flag for the commit message.

You need to update the `travis.yml` to do so.

**Comment by toorusr** [comment]
Is this still important because we are not using travis anymore?

**Comment by minthemiddle** [comment]
Thanks for pointing out, @toorusr, it is not important any longer and can get closed.
