### ISSUE TITLE
Fix: Move testimonials from home page to collection

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/cdweb1801#8]
- Testimonials are an own [Collection](http://jigsaw.tighten.co/docs/collections/)
- The three testimonials on the homepage (`/`) are static text and not part of the collection yet
- They should be moved to the collection
- There should be a dynamic output of the 3 latest testimonials (or 3 random ones)

**Comment by toorusr** [comment]
@minthemiddle Fix #149

**Comment by toorusr** [comment]
Fix #149
