### ISSUE TITLE
Update: Jigsaw to latest version

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/cdweb1801#87]
- We run Jigsaw v1.0.9
- The latest version is [v1.1.4](https://github.com/tightenco/jigsaw/releases/tag/v1.1.4)
- This version is required to fix some issues, such as #11 
- There is no explanation on how to actually upgrade on [Jigsaw's official upgrading site](http://jigsaw.tighten.co/docs/upgrading/) - but just workarounds for common errors
- It does not suffice to edit `composer.json`, delete the `vendor` folder and re-run `composer install`
- This should be tried and the whole page be tested

**Comment by minthemiddle** [comment]
As there is no reference, I also opened an issue at [Jigsaw's repo](https://github.com/tightenco/jigsaw/issues/209)

**Comment by minthemiddle** [comment]
It should be as easy as `composer update` and push the new `composer.lock` to bump the version.

**Comment by toorusr** [comment]
@minthemiddle Fix #156

**Comment by toorusr** [comment]
Fix #156
