### ISSUE TITLE
Add: Blog

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/cdweb1801#9]
The blog can be a place to announce things, e.g. new partnerships.
It can also be a place where participants post longer pieces about what they experience at the camp.

It should be a [collection](http://jigsaw.tighten.co/docs/collections/) and reachable via `/blog`.

**Comment by fronbasal** [comment]
I wrote something like that a few months back: https://github.com/fronbasal/bloggy

**Comment by minthemiddle** [comment]
A blog entry is actually the very same as a camp in `Jigsaw`. It is just a `Markdown` file that extends a layout. No need to pull in another system. Just copy and tweak the camp collection. Blog entries can then be submitted as PR :)

**Comment by fronbasal** [comment]
Awesome :+1:

**Comment by Jubeki** [comment]
If you have a blog how do you add an entry without compiling with jigsaw?
Or do you need to compile every time?

**Comment by fronbasal** [comment]
Because this is a static site it will need to compile again. This process is automated with Travis and Netlify so we do not need to worry about that.
