### ISSUE TITLE
Feature: Add archive for past camps and add dynamic links to homepage

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/cdweb1801#94]
Right now, only few past camps are manually linked from the homepage:

![screen shot 2018-04-12 at 20 05 28](https://user-images.githubusercontent.com/1950766/38695963-17f09c54-3e8e-11e8-88a9-9c7e6aee32b9.png)

The camps are still accessible via their URLs (ex. [1](http://code.design/camps/duesseldorf), [2](http://code.design/hamburg)), but for new visitors it looks as if Code+Design only did one camp before.

Listing all past camps in the footer is not possible (the list would be too long), so the best solution would be to list the past 3 or 4 camps and link to an archive past that lists all past camps.

Mockup:
![screen shot 2018-04-12 at 20 18 24](https://user-images.githubusercontent.com/1950766/38696183-bbfca93c-3e8e-11e8-9d2b-fe80bf10c9f9.png)

This archive should be accessible via `/camps/archive/` and show a set of cards of past camps, maybe like this (or less colorful):

![screen shot 2018-04-12 at 20 29 28](https://user-images.githubusercontent.com/1950766/38696714-44f0c6f0-3e90-11e8-9021-b8251abea2dd.png)

There should be at least the name, date and group picture/camp poster. There should be a link to the actual camp page (don't use the shortlink, e.g. `/camps/duesseldorf` as this will be reused for the next camp but the full URL).

**Comment by minthemiddle** [comment]
@m-lukas Maybe a next project for you?

**Comment by toorusr** [comment]
I'll take the challenge!
