### ISSUE TITLE
Add: Philosophy of the camps

### ISSUE THREAD

**Issue by minthemiddle** [CodeDesignInitiative/cdweb1801#96]
- There is a [written philosophy](https://docs.google.com/document/d/1P-gCD0_dEiRT7fZevmgeJKuEkiirkcVpA5qJnFRRjmk/edit?usp=sharing) about the camps
- This philosophy should be an own page on the website `/camps/philosophie`
- There should be links also from `initiative`
- Maybe there could be a short component that can also be included in all camp pages and elsewhere (just as the camp date component)

**Comment by toorusr** [comment]
How could the `philosophie` page be linked from `initiative`?

**Comment by toorusr** [comment]
@minthemiddle Fix? #148

**Comment by toorusr** [comment]
Fix #148

*But not linked from initiative*
